version: "3.9"
services:
  jupiter:
    image: jupyter/minimal-notebook
    ports:
      - target: 8888
        published: 4444
        protocol: tcp
        mode: host
    networks:
      - my_network_from_compose
    container_name: my-container-jupiter
    environment:
      JUPYTER_TOKEN: "bonjour"
    volumes:
      - .:/home/jovyan/work

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    networks:
      - my_network_from_compose
    container_name: my-container-elasticsearch

  kibana:
    image: kibana:7.2.0
    container_name: my_kibana_from_compose
    networks:
      - my_network_from_compose
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  my_network_from_compose:
